
// 首页的请求
export const GETINDEXRECOMMEND = 'GETINDEXRECOMMEND';
export const GETINDEXBANNER = 'GETINDEXBANNER';
export const GETINDEXSLIDENAV = 'GETINDEXSLIDENAV';
export const GETINDEXTYPE = 'GETINDEXTYPE';
