
// 首页的请求
export const GETINDEXRECOMMEND = 'GETINDEXRECOMMEND';
export const GETINDEXBANNER = 'GETINDEXBANNER';
export const GETINDEXSLIDENAV = 'GETINDEXSLIDENAV';
export const GETINDEXTYPE = 'GETINDEXTYPE';
export const GETINDEXYOULIKE = 'GETINDEXYOULIKE';


// 详情页的q请求

export const GETDETAILSIMG = 'GETDETAILSIMG';
export const GETDETAILSINFO = 'GETDETAILSINFO';